- src/java/org/openzal/zal/Account.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
- src/java/org/openzal/zal/Server.java
Account added methods getLastLogonTime() and setLastLogonTime(String)
Provisioning added method getLastLogonTimestampFrequency()
Server added method isLdapGentimeFractionalSecondsEnabled()
> added methods to update account last logon time

- src/java/org/openzal/zal/InternalOverrideBlobWithMailboxInfo.java
- src/java/org/openzal/zal/Mailbox.java
- src/java/org/openzal/zal/PrimaryStoreBuilder.java
- src/java/org/openzal/zal/StoreManager.java
- src/java/org/openzal/zal/extension/StoreManagerImpl.java
Added method StoreManager.setPrimaryStoreBuilder() to allow to customize behaviour of Zimbra FileBlobStore volumes
> Bulk delete service

- src/java/org/openzal/zal/Element.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
- src/java/org/openzal/zal/soap/SoapTransport.java
- Added XML Element
- Added Provisioning.deleteDistributionListById/Name()
> Element & deleteDistributionList()

- src/java/org/openzal/zal/Mailbox.java
added method getItemByIdFromDumpster
method getAllRevisions() now can handle items in dumpster.
> handle dumpster in Mailbox getItemById and getAllRevisions methods

- src/java/org/openzal/zal/Account.java
- Added setMailQuota(long) method in Account
> [ZX-5547] Drive Migration - Add tests for DriveImportBriefcaseOperation

- src/java/org/openzal/zal/exceptions/ExceptionWrapper.java
- Added VolumeServiceException catch in ExceptionWrapper.wrap()
> Wrap VolumeServiceEception

- src/java/org/openzal/zal/MailboxIndex.java
- src/java/org/openzal/zal/lucene/analysis/Analyzer.java
- src/java/org/openzal/zal/lucene/analysis/AttributeSource.java
- src/java/org/openzal/zal/lucene/analysis/TokenStream.java
- src/java/org/openzal/zal/lucene/analysis/ZimbraAnalyzer.java
- src/java/org/openzal/zal/lucene/analysis/tokenattributes/CharTermAttribute.java
- src/java/org/openzal/zal/lucene/search/BooleanClause.java
- src/java/org/openzal/zal/lucene/search/BooleanQuery.java
- src/java/org/openzal/zal/lucene/search/PhraseQuery.java
- src/java/org/openzal/zal/lucene/search/PrefixQuery.java
**Changes**:
- Added MailboxIndex.getAnalyzer in order to get the correct Analyzer
- Added wrap to Analyzer, AttributeSource, TokenStream, ZimbraAnalyzer, CharTermAttribute, BooleanClause, BooleanQuery, PhraseQuery and PrefixQuery
> [ZX-5541] Added wrap to Lucene Query

- src/java/org/openzal/zal/index/IndexerManager.java
- Fixed InternalMimeHandler.getExtension()
> [ZX-5725] pdf file not indexed

- build
Add support for different JAVA_HOME paths.
> Set automatic JAVA_HOME path recognition

- src/java/org/openzal/zal/Account.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
Add access to `zimbraMailTrashLifetime` and `zimbraPrefTrashLifetime` to manage permanent file deletion
> [ZX-5579] Add access to zimbraMailTrashLifetime and zimbraPrefTrashLifetime

- src/java/org/openzal/zal/calendar/WeekOfMonth.java
- Added EAS conversion in WeekOfMonth
> [MOB-49] Added EAS conversion in WeekOfMonth

- src/java/org/openzal/zal/RedisClientHelper.java
> Added Redis ClientHelper

- src/java/org/openzal/zal/Entry.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
create method on Provisioning named "createFakeAccount" for parsing multi valued attributes
> Bugfix/bck 53 case 00823147 spotler nederland b 2.16

- src/java/org/openzal/zal/AdministrationConstants.java
- src/java/org/openzal/zal/Server.java
- Added USER_SERVICE_URI to AdministrationConstants
- Fixed Server.getAdminURL() and Server.getServiceURL()
> [TEAMS-425]

- src/java/org/openzal/zal/AuthToken.java
* Added ZAL wrap for delegated authentication management in AuthToken
> Added delegated authentication management

- src/java/org/openzal/zal/ProvisioningImp.java
Added constant A_zimbraIsExternalVirtualAccount as wrapping of zimbra LDAP key
> Wrap constant zimbraIsExternalVirtualAccount 

- src/java/org/openzal/zal/calendar/Invite.java
Added MimeMessage to method getRecurrencesInvitees for retrieving it from memory insead of store
> [BCK-120] Fix error on restoring calendar items from backup

- builder/src/ZalBuilder.java
- src/java/org/openzal/zal/Domain.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
Added new constant about zimbra default calendar id
> Bugfix/bck 125 case 00848644 m1 net limited   r

- src/java/org/openzal/zal/BlobBuilder.java
- src/java/org/openzal/zal/BlobBuilderWrap.java
- src/java/org/openzal/zal/FileBlobPrimaryStore.java
- src/java/org/openzal/zal/InternalOverrideFactory.java
- src/java/org/openzal/zal/InternalOverrideVolumeBlob.java
- src/java/org/openzal/zal/MailboxListenerWrapper.java
- src/java/org/openzal/zal/PrimaryStore.java
- src/java/org/openzal/zal/calendar/Invite.java
- src/java/org/openzal/zal/extension/InternalOverrideBlobBuilder.java
- src/java/org/openzal/zal/extension/InternalOverrideStoreManager.java
Added wrappers for BlobBuilder
> [PS-93] primary storage fails when saving s3 store

- src/java/org/openzal/zal/Mailbox.java
- src/java/org/openzal/zal/MailboxListenerWrapper.java
- src/java/org/openzal/zal/ProvisioningImp.java
* Added getContacts in mailbox for retriving auto contacts
* Added wrap for A_zimbraFeatureGalAutoCompleteEnabled and A_zimbraFeatureGalEnabled
> Added getContacts and wrapped GAL attributes

- src/java/org/openzal/zal/soap/InternalAdminDocumentHandler.java
- src/java/org/openzal/zal/soap/InternalDocumentHandler.java
- src/java/org/openzal/zal/soap/InternalDocumentHelper.java
- src/java/org/openzal/zal/soap/InternalOverrideAdminDocumentHandler.java
- src/java/org/openzal/zal/soap/InternalOverrideDocumentHandler.java
- src/java/org/openzal/zal/soap/ZimbraContext.java
- src/java/org/openzal/zal/soap/ZimbraContextImpl.java
- src/java/org/openzal/zal/soap/ZimbraContextSimple.java
- Added Proxier to InternalDocumentHandler for proxing SOAP requests
> Added Proxier to InternalDocumentHandler for proxing SOAP requests

- src/java/org/openzal/zal/calendar/Invite.java
- Convert the Zimbra's Invite Rsvp in a primitive type
> [MOB-94] Resolve a NullPointerException on Invite.getRsvp()

- src/java/org/openzal/zal/Mailbox.java
- src/java/org/openzal/zal/Provisioning.java
- src/java/org/openzal/zal/ProvisioningImp.java
- Cleanup IOException from Mailbox.java
- Added galSearch method that allows to specify the search domain in
ProvisioningImp and interface
> [TEAMS-1059] Cleanup unused exceptions and add new galSearch method

- src/java/org/openzal/zal/calendar/InviteFactory.java
- throw exception if start time is in the future and end time not present
- use time unit to specify 30 in milliseconds
> [MOB-166] Manage invite creation

- src/java/org/openzal/zal/Folder.java
- src/java/org/openzal/zal/Mailbox.java
- src/java/org/openzal/zal/ProvisioningImp.java
- src/java/org/openzal/zal/RetentionPolicy.java
Not sure if destination branch is correct.
> Mob 309 eas autocomplete

- pom.xml
- version.sh
- add plugin to retrieve commit id 
- updated zimbra jar dependencies
- add deploy logic
- fix manifest creation
- include VolumeBlobProxy logic
> [BB-29] Improve POM

- pom.xml
I suggest using the same plugin for all projects
> [BB-23] Change plugin to retrieve commit id 

- packages/PKGBUILD
- pom.xml
Released the ZAL for Carbonio version 22.3.0
> Carbonio 22.3.0

- Jenkinsfile
- packages/PKGBUILD
- pom.xml
- src/java/org/openzal/zal/BuildProperties.java
- src/java/org/openzal/zal/ZalVersion.java
- src/java/org/openzal/zal/extension/ZalEntrypointImpl.java
- Add support for multiple ZAL versions
- Add dev profile and classifier
- Add plugin to manage build properties
- Add packaging logic
> Improve build

- Jenkinsfile
- packages/PKGBUILD
- pom.xml
- src/java/org/openzal/zal/ProvisioningImp.java
Added a new constant in ProvisioningImp for the new attribute on Ldap
> feat: [TEAMS-3737] Add carbonioChatsVideoServerRecordingEnabled constant

- Jenkinsfile
- packages/PKGBUILD
- yap.json
This introduce `epoch` variable support
> chore(IN-627): usage of new pacur agent (yap)
